In [ ]:
#Import das bibliotecas
import pandas as pd

In [ ]:
#Acessadno o arquivo csv
titanic = pd.read_csv('titanic.csv')
titanic

In [ ]:
# Fazendo um filtro para selecionar apenas algumas colunas
# Minha solução
titanic = titanic[['Name', 'Age', 'Sex', 'Pclass', 'Survived']]
titanic

# Solução professor
filter1 = titanic[['Name', 'Age', 'Sex', 'Pclass', 'Survived']]
filter1

,Name,Age,Sex,Pclass,Survived
730,"Allen, Miss. Elisabeth Walton",29.0,female,1,1
275,"Andrews, Miss. Kornelia Theodosia",63.0,female,1,1
571,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",53.0,female,1,1
700,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",18.0,female,1,1
369,"Aubart, Mme. Leontine Pauline",24.0,female,1,1
...,...,...,...,...,...
258,"Ward, Miss. Anna",35.0,female,1,1
366,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",60.0,female,1,1
318,"Wick, Miss. Mary Natalie",31.0,female,1,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,female,1,1
325,"Young, Miss. Marie Grice",36.0,female,1,1

In [ ]:
#Fazendo um filtro para pegar apenas o sexo feminino

# MInha solução
titanic = titanic[titanic['Sex'] == 'female']
titanic

# Solução professor
filter1 = filter1.loc[(filter1['Sex'] == 'female') & (filter1['Pclass'] == 1) & (filter1['Survived'] == 1)]
filter1

,Name,Age,Sex,Pclass,Survived
730,"Allen, Miss. Elisabeth Walton",29.0,female,1,1
275,"Andrews, Miss. Kornelia Theodosia",63.0,female,1,1
571,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",53.0,female,1,1
700,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",18.0,female,1,1
369,"Aubart, Mme. Leontine Pauline",24.0,female,1,1
...,...,...,...,...,...
258,"Ward, Miss. Anna",35.0,female,1,1
366,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",60.0,female,1,1
318,"Wick, Miss. Mary Natalie",31.0,female,1,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,female,1,1
325,"Young, Miss. Marie Grice",36.0,female,1,1

In [ ]:
#Filtro para pegar apenas a primeira classe
titanic = titanic[titanic['Pclass'] == 1]
titanic

In [ ]:
#Filtro para pegar apenas os sobreviventes
titanic = titanic[titanic['Survived'] == 1]
titanic

In [ ]:
# Deixando em ordem alfabetica
#Minha solução
titanic = titanic.sort_values(by='Name')
titanic

#Solução professor
filter1 = filter1.sort_values(by='Name')
filter1

In [ ]:
# Salvando em um novo arquivo csv
titanic.to_csv('titanic_result.csv', index=False)